### ISSUE TITLE
FAIR Checklist

### ISSUE THREAD

**Issue by megasanjay** [megasanjay/test-repo#18]
# Check your compliance with the FAIR-BioRS guidelines

This issue is your repository's dashboard for all things FAIR. You can read the [documentation](https://docs.codefair.io/dashboard) to learn more.

## License

Any open license requests that were created are listed here. You may edit the license and push it when you are happy with the terms.

 - [x] 🔨License request - [ejtPAF5hNTEhB8MfXsbcw](https://codefair.io/add/license/ejtPAF5hNTEhB8MfXsbcw)
  - [ ] 📬 License request - [OOSB0BrTziY2oC5hmcmXp](https://codefair.io/add/license/OOSB0BrTziY2oC5hmcmXp) - #17
 - [ ]  🔔Check this box to create a new license workflow. 🔔

## Codemeta

Any open requests for the generation of the codemeta files are listed here. 

## History

All actions taken with codefair are always listed here for future inspections. 

<details><summary>License</summary>

 - `big-red-cat` - [`TEhB8M`](https://codefair.io/add/license/TEhB8M) - PR #17 

</details>

<details><summary>Codemeta</summary>

 - `small-blue-dog` - [`AF5hN`](https://codefair.io/add/license/AF5hN) - PR #13 

</details>

---

- [ ] Check this box to trigger a request for codefair to run again on this repository. This will also refresh this dashboard
